---
require:
  - rubocop-rails
  - rubocop-rspec
inherit_from:
  - ./config/rubocop-default.yml
  - ./config/rubocop-rails.yml
  - ./config/rubocop-rspec.yml
  - ./config/rubocop-govuk-components.yml
  - ./config/rubocop-dsfr-overrides.yml
inherit_mode:
  merge:
    - Exclude
Style/MixinUsage:
  Exclude:
    - spec/spec_helper.rb
