---
inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7.6

Style/HashSyntax:
  EnforcedShorthandSyntax: never # for ruby 3.0 support

Metrics/ParameterLists:
  Enabled: False

RSpec/ExampleLength:
  Enabled: False

RSpec/RepeatedExampleGroupBody:
  Enabled: False

Naming/FileName:
  Exclude:
    - guide/Rules
