name: Deploy Guide to GitHub Pages
on:
  push:
    branches:
      - main
      - feature/use-gh-actions-deploy-pages
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Upload static site
    steps:
      - uses: actions/checkout@v4
      - name: Install Ruby & gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.3.6
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: make build-guide
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
